FROM eurodatacube/jupyter-user-base-g:0

ARG DOCKER_TAG

ENV KERNEL_NAME=eurodatacube-gpu-${DOCKER_TAG}

# install environment
ADD gpu-environment.yaml .
RUN conda config --system --set channel_priority flexible && \
    conda env create --file gpu-environment.yaml -n "${KERNEL_NAME}" && \
    conda config --system --set channel_priority strict && \
    conda clean --all -f -y && \
    rm gpu-environment.yaml && \
    fix-permissions /home/$NB_USER

# install kernel
USER root
RUN conda run -n "${KERNEL_NAME}" python -m ipykernel install --name "${KERNEL_NAME}" --display-name "EuroDataCube GPU ${DOCKER_TAG} (Python 3)"
USER $NB_UID

# install edc from base image (TODO: make it into package, installable from git)
RUN cp -r /opt/conda/lib/python3.7/site-packages/edc /opt/conda/envs/"${KERNEL_NAME}"/lib/python*/site-packages
