ARG BASE_IMAGE_VERSION
FROM eurodatacube/jupyter-user-base:$BASE_IMAGE_VERSION

ARG KERNEL_VERSION

ENV KERNEL_NAME=eurodatacube-${KERNEL_VERSION}

ADD base-environment.yaml .
RUN conda env create --file base-environment.yaml -n ${KERNEL_NAME} \
    && conda clean --all -f -y

USER root
RUN conda run -n ${KERNEL_NAME} python -m ipykernel install --name ${KERNEL_NAME} --display-name "EuroDataCube ${KERNEL_VERSION} (Python 3)"
USER $NB_UID

# install edc from base image (TODO: make it into package, installable from git)
RUN cp -r /opt/conda/lib/python3.7/site-packages/edc /opt/conda/envs/${KERNEL_NAME}/lib/python*/site-packages
