ARG BASE_CONTAINER=jupyter/scipy-notebook:7a3e968dd212
FROM $BASE_CONTAINER

USER $NB_UID

RUN conda install --quiet --yes oauthlib gdal fiona rasterio shapely && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER 

RUN pip install requests_oauthlib && \
    pip install git+https://github.com/sentinel-hub/sentinelhub-py.git@feat/processing-api && \
    pip install git+https://github.com/dcs4cop/xcube && \
    pip install git+https://github.com/dcs4cop/xcube-sh && \
    fix-permissions /home/$NB_USER 

RUN touch welcome.txt

USER $NB_UID