FROM eurodatacube/jupyter-user-g:0.21.3-dev-8

# add and install environments
ADD kernel-dashboard-race.yaml .
#ADD kernel-dashboard-xcube-geodb.yaml .
ADD kernel-dashboard-no2ts.yaml .

RUN pip config set global.cache-dir false && \
    conda config --system --set channel_priority flexible && \
    conda env create --file kernel-dashboard-race.yaml -n race && \
#    conda env create --file kernel-dashboard-xcube-geodb.yaml -n xcube_geodb && \
    conda env create --file kernel-dashboard-no2ts.yaml -n no2ts && \
    conda config --system --set channel_priority strict && \
    conda clean --all -f -y && \
    pip config set global.cache-dir true && \
    rm kernel-dashboard-race.yaml && \
#    rm kernel-dashboard-xcube-geodb.yaml && \
    rm kernel-dashboard-no2ts.yaml && \
    fix-permissions /home/$NB_USER

USER root

# install kernels
RUN conda run -n "race" python -m ipykernel install --name "race" --display-name "dashboard race (Python3)"
#RUN conda run -n "xcube_geodb" python -m ipykernel install --name "xcube_geodb" --display-name "dashboard xcube_geodb (Python3)"
#no ipykernel RUN conda run -n "no2ts" python -m ipykernel install --name "no2ts" --display-name "dashboard no2ts (Python3)" 

USER $NB_UID
