FROM eurodatacube/jupyter-user-base:0

ARG DOCKER_TAG

ENV KERNEL_NAME=eurodatacube-${DOCKER_TAG}

# install environment
ADD base-environment.yaml .
RUN conda env create --file base-environment.yaml -n "${KERNEL_NAME}" \
    && conda clean --all -f -y \
    && rm base-environment.yaml

# install kernel
USER root
RUN conda run -n "${KERNEL_NAME}" python -m ipykernel install --name "${KERNEL_NAME}" --display-name "EuroDataCube ${DOCKER_TAG} (Python 3)"
USER $NB_UID

# install edc from base image (TODO: make it into package, installable from git)
RUN cp -r /opt/conda/lib/python3.7/site-packages/edc /opt/conda/envs/"${KERNEL_NAME}"/lib/python*/site-packages
