FROM eurodatacube/jupyter-user:2021.12

# Hotfix latest image
# We can't just fix the dockerfile because rebuilding it
# will upgrade some dependencies
USER root
RUN apt-get update --yes && \
    apt-get install --yes --reinstall \
    ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
USER $NB_UID
