FROM eurodatacube/jupyter-user-base-g:0

ARG DOCKER_TAG

ENV ENV_NAME=eurodatacube-gpu-${DOCKER_TAG}

# install environment
ADD kernel-edc-gpu-environment.yaml .
RUN pip config set global.cache-dir false && \
    conda config --system --set channel_priority flexible && \
    conda env create --file kernel-edc-gpu-environment.yaml -n "${ENV_NAME}" && \
    conda config --system --set channel_priority strict && \
    conda clean --all -f -y && \
    pip config set global.cache-dir true && \
    rm kernel-edc-gpu-environment.yaml && \
    fix-permissions /home/$NB_USER

USER root
# Activate environment by default in interactive shells
RUN echo "source activate $ENV_NAME" >> /etc/bash.bashrc

# install kernel
RUN conda run -n "${ENV_NAME}" python -m ipykernel install --name "EDC-GPU" --display-name "EDC-GPU ${DOCKER_TAG} (Python3)"

# we need to patch the kernel.json to set up PATH :(
# by default, the kernel bin dir is not included in PATH
# when the kernel executes a notebook, but we need it for sentinelhub.config
# https://github.com/jupyter/notebook/issues/4527
# https://github.com/ipython/ipykernel/issues/395
# since we already have that, also adding version to the metadata for edc-jlab
RUN python3 -c "\
import os; \
import json; \
env_name = os.environ['ENV_NAME']; \
new_path = f'/opt/conda/envs/{env_name}/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'; \
kernel_json = f'/usr/local/share/jupyter/kernels/edc-gpu/kernel.json'; \
update = {'env': {'PATH': new_path}, 'metadata': {'version': '${DOCKER_TAG}'}}; \
json.dump({**json.load(open(kernel_json)), **update}, open(kernel_json, 'w'), indent=4)"

ADD jupyter-user/edc.py .
RUN mv edc.py /opt/conda/envs/"${ENV_NAME}"/lib/python*/site-packages
USER $NB_UID


# Remove jupyterlab-git extension due to performance reasons
# https://github.com/jupyterlab/jupyterlab-git/issues/703
# https://github.com/jupyterlab/jupyterlab-git/issues/667
# (it is already removed from the base image, but we didn't yet tag and build a new version)
# also update edc-jlab (move this to base image asap)
RUN jupyter labextension uninstall @jupyterlab/git --no-build && \
    jupyter labextension install edc-jlab@0.5.4 --no-build && \
    jupyter lab build && \
    npm cache clean --force && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
    rm -rf /home/$NB_USER/.cache/yarn && \
    rm -rf /home/$NB_USER/.node-gyp
