name: kernel-edc
channels:
  - conda-forge
  - defaults
dependencies:
  # platform basic requirement
  - ipykernel=5.3.0

  # from jupyter/scipy-notebook
  - 'beautifulsoup4=4.9.*'
  - 'conda-forge::blas=*=openblas'
  - 'bokeh=2.1.*'
  - 'bottleneck=1.3.*'
  - 'cloudpickle=1.5.*'
  - 'cython=0.29.*'
  - 'dask=2.20.*'
  - 'dill=0.3.*'
  - 'h5py=2.10.*'
  - 'hdf5=1.10.*'
  - 'ipywidgets=7.5.*'
  - 'ipympl=0.5.*'
  - 'matplotlib-base=3.2.*'
  - 'numba=0.48.*'
  - 'numexpr=2.7.*'
  - 'pandas=1.0.*'
  - 'patsy=0.5.*'
  - 'protobuf=3.12.*'
  - 'pytables=3.6.*'
  - 'scikit-image=0.17.*'
  - 'scikit-learn=0.23.*'
  - 'scipy=1.5.*'
  - 'seaborn=0.10.*'
  - 'sqlalchemy=1.3.*'
  - 'statsmodels=0.11.*'
  - 'sympy=1.6.*'
  - 'vincent=0.4.*'
  - 'xlrd=1.2.*'

  # edc platform
  - pyyaml
  - setuptools
  - cmake
  - cffi
  - python-dotenv
  - oauthlib
  - requests-oauthlib
  - gdal
  - fiona
  - rasterio
  - shapely
  - xarray==0.15.0
  - zarr
  - psycopg2
  - geopandas=0.6.1
  - geojson
  - ipyleaflet
  - cartopy
  - tqdm
  - lightgbm
  - graphviz
  - numba
  - llvmlite
  - descartes
  - nbdime
  - papermill
  - s3fs
  - netcdf4
  - pip
  - pip:
    - eo-learn==0.7.2
    - git+https://github.com/dcs4cop/xcube@87c0c3ae34cac3c2018d290851b89d400e3a819e
    - git+https://github.com/dcs4cop/xcube-sh@832cd809857fccca8b23eb474c3fce31067513d3
    - git+https://github.com/dcs4cop/xcube-geodb@22c31e9c2982fadc8d42ee1be0693849630800a7
    - git+https://github.com/dcs4cop/xcube-gen@104e310324f8affe4cd7f002efc04b8426b5bf8a
