name: kernel-edc
channels:
  - conda-forge
  - defaults
dependencies:
  # platform basic requirement
  - ipykernel=5.3.4

  # from jupyter/scipy-notebook
  - 'beautifulsoup4=4.9.*'
  - 'conda-forge::blas=*=openblas'
  - 'bokeh=2.2.*'
  - 'bottleneck=1.3.*'
  - 'cloudpickle=1.6.*'
  - 'cython=0.29.*'
  - 'dask=2.30.*'
  - 'dill=0.3.*'
  - 'h5py=2.10.*'
  - 'ipywidgets=7.5.*'
  - 'ipympl=0.5.*'
  - 'matplotlib-base=3.3.*'
  - 'numba=0.51.*'
  - 'numexpr=2.7.*'
  - 'pandas=1.1.*'
  - 'patsy=0.5.*'
  - 'protobuf=3.13.*'
  - 'pytables=3.6.*'
  - 'scikit-image=0.17.*'
  - 'scikit-learn=0.23.*'
  - 'scipy=1.5.*'
  - 'seaborn=0.11.*'
  - 'sqlalchemy=1.3.*'
  - 'statsmodels=0.12.*'
  - 'sympy=1.6.*'
  - 'vincent=0.4.*'
  - 'xlrd=1.2.*'

  # edc platform
  - pyyaml
  - setuptools
  - cmake
  - cffi
  - python-dotenv
  - oauthlib
  - requests-oauthlib
  - gdal
  - fiona
  - rasterio
  - shapely
  - xarray==0.16.0
  - zarr
  - psycopg2
  - geopandas=0.6.1
  - geojson
  - ipyleaflet
  - cartopy
  - tqdm
  - lightgbm
  - graphviz
  - numba
  - llvmlite
  - descartes
  - nbdime
  - papermill
  - s3fs
  - netcdf4

  - xcube==0.5.1
  - xcube_geodb==0.1.10
  - pip
  - pip:
    - eo-learn==0.7.2
    - git+https://github.com/dcs4cop/xcube-sh@95c89e6cb3fc3023582855a65894191d25b80a85
    - git+https://github.com/dcs4cop/xcube-gen@104e310324f8affe4cd7f002efc04b8426b5bf8a

  # rhea group
  - wget
  - imutils
  - addict
  - yapf
  - lxml
