name: kernel-edc
channels:
  - conda-forge
  - defaults
dependencies:
  # platform basic requirement
  - ipykernel

  # libraries from old kernel which seem useful
  - cartopy
  - geojson
  - h5py
  - ipyleaflet
  - ipywidgets
  - jupyterlab_widgets
  - openblas
  - protobuf
  - psycopg2
  - sympy
  - widgetsnbextension
  - xlrd
  - graphviz

  # edc platform
  - nbdime
  - papermill
  - s3fs
  - scrapbook
  - pip
  - rioxarray  # useful for notebook jobs
  - openpyxl  # recent versions of xlrd can't read xlsx


  - xcube==0.9.1
  - xcube-sh==0.9.2
  - xcube_geodb==1.0.2
  - xcube-cci==0.9.3
  - xcube-cds==0.9.1
  - nc-time-axis

  # we delay the upgrade to python 3.9 for consistency with the gpu image
  # and general afraidness
  - python<3.9


  # NOTE: there can only be 1 pip block in a conda env
  - pip:
    # edc
    - git+https://github.com/eurodatacube/papermill-kubernetes-job-progess@1d0490d7df0d9e987a6baec4fa5e7d3cf3c3df63

    - eo-learn==0.10.1  # available on conda, but not latest version
    - sentinelhub==3.4.1  # also known as shpy
    - s2cloudless==1.5.0  # available on conda, but not latest version

    # botocore downgrade until this is fixed: https://github.com/dcs4cop/xcube/issues/572
    - botocore==1.20.106
